# Generated by Django 4.0 on 2021-12-22 22:56

from django.db import migrations


def delete_all_existing_events_and_calendars(apps, schema_editor):
    Event = apps.get_model('timers', 'Event')
    Calendar = apps.get_model('timers', 'Calendar')
    db_alias = schema_editor.connection.alias
    Event.objects.using(db_alias).all().delete()
    Calendar.objects.using(db_alias).all().delete()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('timers', '0005_alter_event_calendar'),
    ]

    operations = [
        migrations.RunPython(delete_all_existing_events_and_calendars,
                             do_nothing)
    ]
