# Generated by Django 4.0 on 2021-12-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0006_delete_all_existing_events_and_calendars'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
