# Generated by Django 4.0 on 2021-12-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0007_calendar_id_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(),
        ),
    ]
