# Generated by Django 4.0 on 2021-12-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0008_alter_calendar_id_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
                model_name='calendar',
                name='google_id',
                field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
                model_name='event',
                name='google_id',
                field=models.CharField(max_length=100),
        ),
    ]
