# Generated by Django 4.0 on 2021-12-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0009_alter_calendar_google_id_alter_calendar_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='summary',
            new_name='name',
        ),
    ]
