# Generated by Django 4.0 on 2021-12-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0010_rename_summary_event_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('google_id', 'user'), name="Unique 'google_id' per user"),
        ),
    ]
