# Generated by Django 4.0 on 2021-12-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', "0011_calendar_unique 'google_id' per user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('google_id', 'calendar'), name="Unique 'google_id' per calendar"),
        ),
    ]
